version: '3.1'

services:
  java-server:
    image: ghcr.io/eat-it-team/log-social-back/log-social-back
    ports:
      - 8080:8080
    depends_on:
      - new_mongodb
  new_mongodb:
    image: mongo:4
    container_name: new_mongodb
    environment:
      - PUID=1000
      - PGID=1000
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin
      - MONGO_INITDB_DATABASE=poor_registry
    #ports:
    #  - "27017:27017"
    volumes:
      - ../docker-prod/volumes/mongo:/data/db
      - ../docker-prod/volumes/init/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    restart: unless-stopped
