# This is a basic workflow to help you get started with Actions

name: Java CI with Maven

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Set up JDK 8
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'adopt'
      
      - name: Build with Maven
        run: mvn -B clean install
        #run: mvn -B package --file pom.xml

  #     Set global environment variables:
      - name: set global env
        id: global_env
        run: |
          echo "::set-output name=IMAGE_NAME::${GITHUB_REPOSITORY#*/}"
          echo "::set-output name=DOCKERHUB_IMAGE_NAME::ghcr.io/${GITHUB_REPOSITORY}/${GITHUB_REPOSITORY#*/}"
  #     Build Docker image:
      - name: Build and tag image
        run: |
          docker build -t "${{ steps.global_env.outputs.DOCKERHUB_IMAGE_NAME }}:latest" -t "${{ steps.global_env.outputs.DOCKERHUB_IMAGE_NAME }}:${GITHUB_SHA::8}" .
  #    - name: Docker login
  #      run: docker login ghcr.io -u $GITHUB_ACTOR -p ${{secrets.GITHUB_TOKEN}}

      - name: Log into registry
        # This is where you will update the PAT to GITHUB_TOKEN
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
        #run: echo "${{ secrets.CR_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

  #     Publish image to github package repository:
      - name: Publish image
        env:
          IMAGE_NAME: $GITHUB_REPOSITORY
        run: docker push "ghcr.io/$GITHUB_REPOSITORY/${{ steps.global_env.outputs.IMAGE_NAME }}"

# ssh and docker-compose

      - name: copy docker-compose via ssh key
        uses: appleboy/scp-action@master
        with:
          host: hackathon.rodial.pro
          username: root
          key: ${{ secrets.HACKATHON_SSH }}
          rm: true
          source: "docker-prod/docker-compose.yaml"
          target: "log-social-back"

      - name: executing remote ssh commands using key
        uses: appleboy/ssh-action@master
        with:
          host: hackathon.rodial.pro
          username: root
          key: ${{ secrets.HACKATHON_SSH }}
          script: |
            cd log-social-back/docker-prod
            docker-compose pull mongodb
            echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin 
            docker-compose pull java-server
            docker-compose up -d
